/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package techquiz.gui;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import techquiz.dao.ExamDAO;
import techquiz.pojo.ExamPOJO;
import techquiz.pojo.UserProfile;

/**
 *
 * @author SHUBHAM MANMOHAN
 */
public class EditPaperFrame extends javax.swing.JFrame {

    String subjectName;
    /**
     * Creates new form EditPaperFrame
     */
    public EditPaperFrame() {
        this.setTitle("Edit Paper - "+"OnlineTechQuizApp");
        initComponents();
        this.setLocationRelativeTo(null);
        lblUser.setText("Hello "+UserProfile.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editPaperPanel = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblPaperEditing = new javax.swing.JLabel();
        lblSetPaper = new javax.swing.JLabel();
        lblChooseSubject = new javax.swing.JLabel();
        lblChooseExamId = new javax.swing.JLabel();
        jcbSubject = new javax.swing.JComboBox();
        jcbExamId = new javax.swing.JComboBox();
        btnEditQuestions = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        editPaperPanel.setBackground(new java.awt.Color(0, 102, 102));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techquiz/gui/appimages/examicon - Copy.png"))); // NOI18N

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 102, 0));
        lblUser.setText("Hello");

        lblLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 102, 0));
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        lblPaperEditing.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblPaperEditing.setForeground(new java.awt.Color(204, 102, 0));
        lblPaperEditing.setText("PAPER EDITING PANEL");

        lblSetPaper.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSetPaper.setForeground(new java.awt.Color(255, 102, 0));
        lblSetPaper.setText("Set Paper Details ::");

        lblChooseSubject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblChooseSubject.setForeground(new java.awt.Color(255, 255, 204));
        lblChooseSubject.setText("Choose The Subject:");

        lblChooseExamId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblChooseExamId.setForeground(new java.awt.Color(255, 255, 204));
        lblChooseExamId.setText("Choose The Exam ID:");

        jcbSubject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbSubject.setMaximumRowCount(4);
        jcbSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "JAVA SE", "JAVA EE", "C++", "C", "PYTHON", ".NET", "DATA STRUCTURE ", "ORACLE", "WEB DEVELOPMENT", "OOP" }));
        jcbSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSubjectActionPerformed(evt);
            }
        });

        jcbExamId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbExamId.setMaximumRowCount(4);
        jcbExamId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        btnEditQuestions.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditQuestions.setForeground(new java.awt.Color(153, 102, 0));
        btnEditQuestions.setText("Edit The Questions");
        btnEditQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditQuestionsActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(153, 102, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editPaperPanelLayout = new javax.swing.GroupLayout(editPaperPanel);
        editPaperPanel.setLayout(editPaperPanelLayout);
        editPaperPanelLayout.setHorizontalGroup(
            editPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPaperPanelLayout.createSequentialGroup()
                .addGroup(editPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPaperPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLogout))
                    .addGroup(editPaperPanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lblPaperEditing, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(editPaperPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(editPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPaperPanelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(editPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editPaperPanelLayout.createSequentialGroup()
                                .addComponent(lblChooseSubject)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(editPaperPanelLayout.createSequentialGroup()
                                .addComponent(lblChooseExamId)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPaperPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addGroup(editPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(editPaperPanelLayout.createSequentialGroup()
                                .addComponent(btnEditQuestions)
                                .addGap(39, 39, 39)
                                .addComponent(btnBack))
                            .addComponent(jcbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbExamId, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPaperPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSetPaper)
                .addGap(220, 220, 220))
        );
        editPaperPanelLayout.setVerticalGroup(
            editPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPaperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(lblLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPaperEditing)
                .addGap(13, 13, 13)
                .addComponent(lblSetPaper)
                .addGap(20, 20, 20)
                .addGroup(editPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPaperPanelLayout.createSequentialGroup()
                        .addComponent(lblChooseSubject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblChooseExamId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbExamId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImage))
                .addGap(34, 34, 34)
                .addGroup(editPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnEditQuestions))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editPaperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(editPaperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
     AdminOptionsFrame adminOption=new AdminOptionsFrame();
     adminOption.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
      lblLogout.setForeground(Color.WHITE);
        Font f=new Font("Tahoma",Font.ITALIC,14);
        lblLogout.setFont(f);
        Cursor c=new Cursor(Cursor.HAND_CURSOR);
        lblLogout.setCursor(c);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
         lblLogout.setForeground(new Color(255,102,0));
         Font f=new Font("Tahoma",Font.BOLD,14);
         lblLogout.setFont(f);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        this.dispose();
        LoginFrame loginFrame=new LoginFrame();
        loginFrame.setVisible(true);
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void jcbSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSubjectActionPerformed
         boolean check=validateInput();
         if(!check)
         {
         JOptionPane.showMessageDialog(null,"Please Select A Subject!!!","Error!!!",JOptionPane.ERROR_MESSAGE);
         jcbExamId.removeAllItems();
         return;
         }
         try
         {
            ArrayList <String> examIdList=ExamDAO.getExamIdBySubject(subjectName);
            if(examIdList.isEmpty())
            {
            JOptionPane.showMessageDialog(null, "No Exam Set For "+subjectName);
            jcbSubject.setSelectedIndex(0);
            jcbExamId.removeAllItems();
            return;
            }
            jcbExamId.removeAllItems();
            for(String examId:examIdList)
            {
            jcbExamId.addItem(examId);
            }
         }
         catch(SQLException ex)
         {
         JOptionPane.showMessageDialog(null, "DB Error!!!","Edit Paper Error!!!",JOptionPane.ERROR_MESSAGE);
         ex.printStackTrace();
         }
    }//GEN-LAST:event_jcbSubjectActionPerformed

    private void btnEditQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditQuestionsActionPerformed
     boolean check=validateInput();
         if(!check)
         {
         JOptionPane.showMessageDialog(null,"Please Select A Subject!!!","Error!!!",JOptionPane.ERROR_MESSAGE);
         return;
         }
         String subject=jcbSubject.getSelectedItem().toString();
         String examId=jcbExamId.getSelectedItem().toString();
         int ans;
         ans=JOptionPane.showConfirmDialog(null, "Are You Sure , You Want To Edit "+subject+"and Exam Id "+examId,"Sure!!!",JOptionPane.YES_NO_OPTION);
         if(ans==JOptionPane.YES_OPTION)
         {
              try
                {
                   int totalQuestion=ExamDAO.getQuestionCountByExam(examId);
     //               System.out.println("Exam ID:"+examId+" total Question: "+totalQuestion);
                   ExamPOJO editExam=new ExamPOJO(examId,subject,totalQuestion);
                   EditQuestionsFrame editQuestion=new EditQuestionsFrame(editExam);
                   editQuestion.setVisible(true);
                   this.dispose();
                }
              catch(SQLException ex)
         {
         JOptionPane.showMessageDialog(null, "DB Error!!!","Edit Paper Error!!!",JOptionPane.ERROR_MESSAGE);
         ex.printStackTrace();
         }
         }
    }//GEN-LAST:event_btnEditQuestionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPaperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPaperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPaperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPaperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPaperFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEditQuestions;
    private javax.swing.JPanel editPaperPanel;
    private javax.swing.JComboBox jcbExamId;
    private javax.swing.JComboBox jcbSubject;
    private javax.swing.JLabel lblChooseExamId;
    private javax.swing.JLabel lblChooseSubject;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblPaperEditing;
    private javax.swing.JLabel lblSetPaper;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables

    private boolean validateInput() {
       if(jcbSubject.getSelectedIndex()==0)
           return false;
       subjectName=jcbSubject.getSelectedItem().toString();
           return true;
    }
}
