/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package techquiz.gui;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import techquiz.dao.ExamDAO;
import techquiz.pojo.ExamPOJO;
import techquiz.pojo.UserProfile;

/**
 *
 * @author SHUBHAM MANMOHAN
 */
public class SetPaperFrame extends javax.swing.JFrame {

    /**
     * Creates new form SetPaperFrame
     */
    public SetPaperFrame() 
    {
        this.setTitle("Set Paper - "+"OnlineTechQuizApp");
        initComponents();
        Color c=new Color(0,102,102);
        btnSetQuestions.setBackground(c);
        btnBack.setBackground(c);
        this.setLocationRelativeTo(null);
        lblUser.setText("Hello "+UserProfile.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPaperPanel = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblPaperSettingPanel = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblSetPaperDetails = new javax.swing.JLabel();
        lblChooseTheSubject = new javax.swing.JLabel();
        lblSetNumberOfQuestions = new javax.swing.JLabel();
        jcbSubject = new javax.swing.JComboBox();
        txtSetNumberOfQuestions = new javax.swing.JTextField();
        btnSetQuestions = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        setPaperPanel.setBackground(new java.awt.Color(0, 102, 102));

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 102, 0));
        lblUser.setText("Hello");

        lblLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 102, 0));
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        lblPaperSettingPanel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblPaperSettingPanel.setForeground(new java.awt.Color(204, 204, 255));
        lblPaperSettingPanel.setText("PAPER SETTING PANEL");

        lblAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techquiz/gui/appimages/questionpaper - Copy.jpg"))); // NOI18N

        lblSetPaperDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSetPaperDetails.setForeground(new java.awt.Color(204, 102, 0));
        lblSetPaperDetails.setText("Set Paper Details  ::");

        lblChooseTheSubject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblChooseTheSubject.setForeground(new java.awt.Color(255, 153, 102));
        lblChooseTheSubject.setText("Choose the Subject :");

        lblSetNumberOfQuestions.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSetNumberOfQuestions.setForeground(new java.awt.Color(255, 153, 102));
        lblSetNumberOfQuestions.setText("Set Number of Questions :");

        jcbSubject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbSubject.setMaximumRowCount(4);
        jcbSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "JAVA SE", "JAVA EE", "C++", "C", "PYTHON", ".NET", "DATA STRUCTURE ", "ORACLE", "WEB DEVELOPMENT", "OOP" }));

        btnSetQuestions.setBackground(new java.awt.Color(0, 102, 153));
        btnSetQuestions.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSetQuestions.setForeground(new java.awt.Color(0, 51, 51));
        btnSetQuestions.setText("Set The Questions");
        btnSetQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetQuestionsActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 102, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 51, 51));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout setPaperPanelLayout = new javax.swing.GroupLayout(setPaperPanel);
        setPaperPanel.setLayout(setPaperPanelLayout);
        setPaperPanelLayout.setHorizontalGroup(
            setPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPaperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(setPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setPaperPanelLayout.createSequentialGroup()
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLogout))
                    .addGroup(setPaperPanelLayout.createSequentialGroup()
                        .addComponent(lblAdmin)
                        .addGroup(setPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(setPaperPanelLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(setPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSetNumberOfQuestions)
                                    .addComponent(lblChooseTheSubject)
                                    .addGroup(setPaperPanelLayout.createSequentialGroup()
                                        .addComponent(btnSetQuestions)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBack))))
                            .addGroup(setPaperPanelLayout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(jcbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setPaperPanelLayout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(txtSetNumberOfQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 112, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(setPaperPanelLayout.createSequentialGroup()
                .addGroup(setPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setPaperPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lblPaperSettingPanel))
                    .addGroup(setPaperPanelLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(lblSetPaperDetails)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        setPaperPanelLayout.setVerticalGroup(
            setPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPaperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(setPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogout))
                .addGap(16, 16, 16)
                .addComponent(lblPaperSettingPanel)
                .addGap(18, 18, 18)
                .addComponent(lblSetPaperDetails)
                .addGap(20, 20, 20)
                .addGroup(setPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAdmin, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, setPaperPanelLayout.createSequentialGroup()
                        .addComponent(lblChooseTheSubject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(lblSetNumberOfQuestions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSetNumberOfQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(setPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetQuestions)
                    .addComponent(btnBack))
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(setPaperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(setPaperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        this.dispose();
        LoginFrame loginFrame=new LoginFrame();
        loginFrame.setVisible(true);
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setForeground(Color.WHITE);
        Font f=new Font("Tahoma",Font.ITALIC,14);
        lblLogout.setFont(f);
        Cursor c=new Cursor(Cursor.HAND_CURSOR);
        lblLogout.setCursor(c);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
         lblLogout.setForeground(new Color(255,102,0));
         Font f=new Font("Tahoma",Font.BOLD,14);
         lblLogout.setFont(f);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void btnSetQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetQuestionsActionPerformed
     String subject=jcbSubject.getSelectedItem().toString();
     try{
     int totalQuestions=Integer.parseInt(txtSetNumberOfQuestions.getText());
     int ans=JOptionPane.showConfirmDialog(null, "You Choose "+subject+" and Total Questions "+totalQuestions+" ? \n Click Yes to Confirm!!!","Confirmation!!1",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
     if(ans==JOptionPane.YES_OPTION)
       {
         try{
             String examId=ExamDAO.getExamId();
             ExamPOJO newExam=new ExamPOJO(examId,subject,totalQuestions);
             SetQuestionsFrame setQuestion=new SetQuestionsFrame(newExam);
             setQuestion.setVisible(true);
             this.dispose();
            }
         catch(SQLException ex)
           {
           JOptionPane.showMessageDialog(null, "Error while connecting to DataBase!!!","DB Error!!!",JOptionPane.ERROR_MESSAGE);
           ex.printStackTrace();
           }
       } 
     }
     catch(NumberFormatException ex){
     JOptionPane.showMessageDialog(null, "Please Enter Digits Only!!!","Input Error!!!",JOptionPane.ERROR_MESSAGE);
     }
     
    }//GEN-LAST:event_btnSetQuestionsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
     AdminOptionsFrame adminOption=new AdminOptionsFrame();
     adminOption.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetPaperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetPaperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetPaperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetPaperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetPaperFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSetQuestions;
    private javax.swing.JComboBox jcbSubject;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblChooseTheSubject;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblPaperSettingPanel;
    private javax.swing.JLabel lblSetNumberOfQuestions;
    private javax.swing.JLabel lblSetPaperDetails;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel setPaperPanel;
    private javax.swing.JTextField txtSetNumberOfQuestions;
    // End of variables declaration//GEN-END:variables
}
